{
 "title": "Redis Cluster Monitoring",
 "tags": [
  "redis",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis Commands Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])",
     "legendFormat": "{{instance}} - Commands/sec"
    }
   ]
  },
  {
   "title": "Redis CPU Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_cpu_sys_seconds_total[1m])\n+ rate(redis_cpu_user_seconds_total[1m])\n",
     "legendFormat": "{{instance}} - Connected Clients"
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{instance}} - Memory Used" }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients",
     "legendFormat": "{{instance}} - Connected Clients"
    }
   ]
  },
  {
   "title": "Total Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_db_keys", "legendFormat": "{{instance}} - {{db}} - Keys" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total[1m])",
     "legendFormat": "{{instance}} - Input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total[1m])",
     "legendFormat": "{{instance}} - Output"
    }
   ]
  }
 ]
}